name: Main Workflow
on: [push]
jobs:
  test_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ubuntu, fedora]
    container:
      image: ${{ matrix.image }}:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          chmod +x ./test.sh
          /bin/bash ./test.sh
