name: Main Workflow
on: [push]
jobs:
  test_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ubuntu, fedora]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          chmod +x /code/test.sh
          docker run --rm -v $(pwd):/code --workdir=/code ${{ matrix.image }}:latest /bin/bash -c "/code/test.sh"
