name: Main Workflow

on:
  push:
    branches: [master]


jobs:
  test_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ubuntu, fedora]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        uses: docker://${{ matrix.image }}:latest
        with:
          entrypoint: /bin/bash
          args: ./test.sh